[project]
name = "luka-website"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "nbconvert>=7.16.6",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
]
